Sys.setenv(TZ="America/New_York")
library(readr)
library(tidyverse)
library(stringr)
library(lubridate)
library(googlesheets)

#dvs_cal_tbl <- read_tsv("/Users/joel/Dropbox/EDC/workshops/fall_2018/fall_2018_workshops.txt", locale = "America/New_York")

#Fall 2018 Workshops
#dvs_cal_tbl <- structure(list(workshop_id = c("4337268", "4349368", "4335566", 
                               "4341120", "4350030", "4337253", "4335574", "4341127", "4335577", 
                               "4350034", "4350882", "4337315", "4428595", "4335582", "4475727", 
                               "4350042", "4350915", "4335586", "4337318", "4335665", "4344635", 
                               "4337320", "4396168", "4337307", "4397616"), date = structure(c(17778, 
                                                                                               17779, 17785, 17786, 17787, 17792, 17793, 17794, 17799, 17799, 
                                                                                               17800, 17806, 17806, 17807, 17812, 17815, 17815, 17820, 17827, 
                                                                                               17834, 17835, 17842, 17843, 17848, 17849), class = "Date"), title = c("Intro to R: Data Transformations, Data Structures, and the Tidyverse", 
                                                                                                                                                                     "Web Mapping", "Building Blocks for Reproducibility: Concepts and Practices", 
                                                                                                                                                                     "Intro to ArcGIS Pro", "Creating Infographics in PowerPoint", 
                                                                                                                                                                     "Visualization in R using ggplot2", "Data Management 101 for Social Scientists", 
                                                                                                                                                                     "Intro to QGIS", "Building Blocks for Reproducibility: RStudio and Git", 
                                                                                                                                                                     "Adobe Illustrator for Diagrams", "Story Maps", "R Markdown: tips for authoring reproducible documents, slide presentations, web dashboards and more", 
                                                                                                                                                                     "Introduction to Stata", "Data Management 101 for Humanists", 
                                                                                                                                                                     "Ethics and Visualization", "Tidy Data in Python with JupyterLab", 
                                                                                                                                                                     "Map Design", "Building Blocks for Reproducibility: GitHub and GitLab", 
                                                                                                                                                                     "Mapping with R", "Building Blocks for Reproducibility: Open Science Framework (OSF)", 
                                                                                                                                                                     "Data Management 101 for Scientists", "Shiny App Development with Dr. Mine Çetinkaya-Rundel", 
                                                                                                                                                                     "Finding a Home for Your Data: An Introduction to Archives & Repositories", 
                                                                                                                                                                     "Tidying hierarchical data from the web with Professor Colin Rundel", 
                                                                                                                                                                     "Building Blocks for Reproducibility: The TIER Protocol"), presenter = c("John Little", 
                                                                                                                                                                                                                                              "Drew Keener", "April Clyburne-Sherin", "Mark Thomas", "Eric Monson", 
                                                                                                                                                                                                                                              "Angela Zoss", "Jen Darragh & Sophia Lafferty-Hess & Lorrie Schmid", 
                                                                                                                                                                                                                                              "Mark Thomas", "John Little", "Eric Monson", "Drew Keener", "John Little", 
                                                                                                                                                                                                                                              "Ryan Denniston", "Jen Darragh, Sophia Lafferty-Hess & Liz Milewicz", 
                                                                                                                                                                                                                                              "Eric Monson & Angela Zoss", "Eric Monson", "Drew Keener", "John Little", 
                                                                                                                                                                                                                                              "John Little", "Jen Darragh & Sophia Lafferty-Hess", "Jen Darragh, Elena Feinstein & Sophia Lafferty-Hess", 
                                                                                                                                                                                                                                              "Mine Çetinkaya-Rundel", "Jen Darragh & Sophia Lafferty-Hess", 
                                                                                                                                                                                                                                              "Professor Colin Rundel", "Jen Darragh & Sophia Lafferty-Hess"
                                                                                                                                                                     ), workshop_duration_minutes = c(120, 120, 120, 120, 120, 120, 
                                                                                                                                                                                                      120, 120, 60, 120, 120, 120, 120, 120, 120, 120, 90, 60, 120, 
                                                                                                                                                                                                      60, 120, 120, 120, 120, 60), workshop_begins = structure(c(1536082200, 
                                                                                                                                                                                                                                                                 1536166800, 1536674400, 1536771600, 1536843600, 1537291800, 1537376400, 
                                                                                                                                                                                                                                                                 1537462800, 1537884000, 1537894800, 1537981200, 1538488800, 1538499600, 
                                                                                                                                                                                                                                                                 1538586000, 1539007200, 1539262800, 1539279000, 1539698400, 1540314000, 
                                                                                                                                                                                                                                                                 1540908000, 1541005200, 1541602800, 1541700000, 1542121200, 1542207600
                                                                                                                                                                                                      ), tzone = "America/New_York", class = c("POSIXct", "POSIXt")), 
               workshop_ends = structure(c(1536089400, 1536174000, 1536681600, 
                                           1536778800, 1536850800, 1537299000, 1537383600, 1537470000, 
                                           1537887600, 1537902000, 1537988400, 1538496000, 1538506800, 
                                           1538593200, 1539014400, 1539270000, 1539284400, 1539702000, 
                                           1540321200, 1540911600, 1541012400, 1541610000, 1541707200, 
                                           1542128400, 1542211200), tzone = "America/New_York", class = c("POSIXct", 
                                                                                                          "POSIXt")), description = c("A gentle introduction to R and the Tidyverse using RStudio. Learn about managing your R projects, data types, variable assignments, data structures, and packages such as: tidyverse (dplyR) and ggvis. Attendees will have the opportunity of supplementing the materials covered in this workshop with free academic access to the interactive training workshops at DataCamp.com.", 
                                                                                                                                      "This introductory workshop will teach you how to easily build interactive, online maps. After discussing general mapping concepts and technologies, we will present step-by-step tutorials for ArcGIS Online, a cloud-based mapping platform. Topics will include aspects of adding data, creating and styling maps, publishing web applications, and using spatial analysis tools.", 
                                                                                                                                      "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. DVS is offering a workshop series that will introduce the concepts, practices and tools that will help increase the reproducibility of your work.", 
                                                                                                                                      "ArcGIS Pro is a newly designed interface as an alternative to the tried-and-true ArcGIS desktop software. It has essentially the same functions, but with more of a MS-Office feel. As a native 64-bit program, it also has superior performance. There are a few nice feature enhancements such as multiple layouts in a single project.  It's more fully integrated with ArcGIS Online, and users will need to have created an Duke ArcGIS Online account. An administrator will activate your ArcGIS Pro license after you've created an ArcGIS Online account.", 
                                                                                                                                      "The “infographics” style of presenting information and telling visual stories is popular both for internal reporting and for trying to reach and teach the general public. There are many desktop and online tools that can be used to compose static infographics, but we will focus on Microsoft PowerPoint because so many people have free access to it on campus and already have some comfort with it as a visual communications tool. This workshop will give a brief introduction to graphic design and storytelling principles, as well as hands-on practice with using PowerPoint to create charts, icons and other vector shapes to combine with text and visualizations to tell compelling and eye-catching data stories. There are no prerequisites, but some experience using PowerPoint will be helpful.", 
                                                                                                                                      "Data science skills are increasingly important for research and industry projects.  With complex data science projects, however, come complex needs for understanding and communicating analysis processes and results.  Ultimately, an analyst's data science toolbox is incomplete without visualization skills.  Incorporating effective visualizations directly into the analysis tool you are using can facilitate quick data exploration, streamline your research process, and improve the reproducibility of your research.", 
                                                                                                                                      "Social scientists work with lots of data in their research, be it qualitative or quantitative, primary or secondary. This workshop will introduce data management practices for social scientists to consider and apply throughout the research lifecycle. Good data management practices pertaining to planning, organization, documentation, storage and backup, sharing, citation, and preservation will be presented through a social sciences lens using discipline-based, concrete examples. While good general data management practices are relevant across disciplines, participants working specifically within the social sciences are the intended audience for this workshop. ", 
                                                                                                                                      "Looking for an open source option for GIS? In this workshop we will demonstrate how to import and analyze data in QGIS and discuss the benefits of using QGIS over other GIS software. In the process, we'll go over some general GIS concepts such as layers, types of GIS files, and projections.", 
                                                                                                                                      "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. DVS is offering a workshop series that will introduce the concepts, practices and tools that will help increase the reproducibility of your work.", 
                                                                                                                                      "In this workshop, you will learn the basics of using Adobe Illustrator, the professional standard in vector graphics software for creating diagrams and infographics. Many people avoid using it because of its steep learning curve, but you will see that it is quite easy to combine simple shapes to create interesting and clear diagrams, and to give all your work that professional edge. There are no prerequisites.", 
                                                                                                                                      "This workshop will help you get started telling stories with maps using the Esri Story Map platform. This easy-to-use application integrates maps with narrative text, images, and videos to provide a powerful communication tool for any project with a geographic component. We will explore the capabilities of Story Maps, share best practices for designing effective stories, and guide participants through the process of creating their own Story Map.", 
                                                                                                                                      "Learn how to use this lightweight markup language to compose reproducible reports in many formats: MS Word, PDF, R Notebooks, Web Pages, Slide Presentations, and more. ", 
                                                                                                                                      "Introduction to Stata focuses on the core concepts of using Stata. This workshop provides a hands on overview of how to load, manage, and analyze data using Stata. The workshop will also include a brief introduction to Stata graphics as well. No previous experience with Stata is required.", 
                                                                                                                                      "Humanists work with various media, content and materials (sources) as part of their research. These sources can be considered data. This workshop will introduce data management practices for humanities researchers to consider and apply throughout the research lifecycle.  Good data management practices pertaining to planning, organization, documentation, storage and backup, sharing, citation, and preservation will be presented through a humanities lens with discipline-based, concrete examples. While general good data management practices are relevant across disciplines, participants working specifically within the humanities are the intended audience for this workshop.", 
                                                                                                                                      "Data visualization is an increasingly important skill for researchers in all disciplines, but it is easy to focus more on the mechanics of creating visualizations than on how visualizations relate to ethics. This session introduces participants to core ideas in the ethics of visualization - designing to avoid distortion, designing ethically for broad user communities, developing empathy for people represented within the data, and using reproducibility to increase the transparency of design. This workshop does not require a laptop. (This workshop offers RCR credit.)", 
                                                                                                                                      "Python can be a great option for exploration, analysis and visualization of tabular data, like spreadsheets and CSV files, if you know which tools to use and how to get started. This workshop will take you through some practical examples of using Python and the Pandas module to load data, transform it into a standard “tidy” format, and visualize it with Seaborn (or another similar module). We will also introduce you to working in JupyterLab, the exiting new flexible programming environment which will eventually replace Jupyter Notebooks.", 
                                                                                                                                      "Making maps is a creative rather than a purely technical process. Even if you can expertly use the latest and most advanced tools, you still have to make design decisions based on your specific audience, data, and goals. This workshop will present an overview of concepts in cartography and provide practical techniques for creating effective, visually appealing maps. We will explore design principles by analyzing plenty of examples. No specific software experience or GIS knowledge is required.", 
                                                                                                                                      "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. DVS is offering a workshop series that will introduce the concepts, practices and tools that will help increase the reproducibility of your work.", 
                                                                                                                                      "R has become a popular and reproducible option for supporting spatial and statistical analysis. This hands-on workshop will demonstrate how to plot x/y coordinates; how to generate thematic chloropleths with US Census and other federal data; import shapefiles; and create interactive maps on the web.", 
                                                                                                                                      "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. DVS is offering a workshop series that will introduce the concepts, practices and tools that will help increase the reproducibility of your work.", 
                                                                                                                                      "Scientists work with lots of data both big and small, and in many formats and systems. This workshop will introduce data management practices for scientists to consider and apply throughout the research lifecycle. Good data management practices pertaining to planning, organization, documentation, storage and backup, sharing, citation, and preservation will be presented through a sciences lens using discipline-based, concrete examples. While good general data management practices are relevant across disciplines, participants working specifically within the sciences are the intended audience for this workshop.", 
                                                                                                                                      "Shiny is an R package that makes it easy to build interactive web apps straight from R. You can host stand-alone apps on a webpage or embed them in R Markdown documents or build dashboards. This short course will introduce you to building web applications with Shiny, reactive programming, and customizing and deploying your apps for others to use.", 
                                                                                                                                      "Publishing and preserving research data within a trusted repository helps researchers comply with funder and journal data sharing policies, supports the discovery of and access to data, and can result in more visibility and higher impact for research projects. This workshop will provide an overview of the different types of repositories and the overall role of repositories within the data sharing landscape. Key repositories in various disciplines will be explored and attendees will learn about resources for locating and assessing repositories. Attendees will also have an opportunity to locate appropriate repositories for their own research.", 
                                                                                                                                      "Gathering data from the web presents unique challenges to the researcher. Only rarely is the data we need available as a tidy rectangle that can be easily imported and directly analyzed. During this workshop we will discuss some of the common data formats (e.g. json, xml) and data sources (e.g. APIs, web scraping) as well as the tools / packages / best practices for ingesting these data using the R programming language.", 
                                                                                                                                      "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. DVS is offering a workshop series that will introduce the concepts, practices and tools that will help increase the reproducibility of your work."
                                                                                                          ), registration_link = c("https://duke.libcal.com/event/4337268", 
                                                                                                                                   "https://duke.libcal.com/event/4349368", "https://duke.libcal.com/event/4335566", 
                                                                                                                                   "https://duke.libcal.com/event/4341120", "https://duke.libcal.com/event/4350030", 
                                                                                                                                   "https://duke.libcal.com/event/4337253", "https://duke.libcal.com/event/4335574", 
                                                                                                                                   "https://duke.libcal.com/event/4341127", "https://duke.libcal.com/event/4335577", 
                                                                                                                                   "https://duke.libcal.com/event/4350034", "https://duke.libcal.com/event/4350882", 
                                                                                                                                   "https://duke.libcal.com/event/4337315", "https://duke.libcal.com/event/4428595", 
                                                                                                                                   "https://duke.libcal.com/event/4335582", "https://duke.libcal.com/event/4475727", 
                                                                                                                                   "https://duke.libcal.com/event/4350042", "https://duke.libcal.com/event/4350915", 
                                                                                                                                   "https://duke.libcal.com/event/4335586", "https://duke.libcal.com/event/4337318", 
                                                                                                                                   "https://duke.libcal.com/event/4335665", "https://duke.libcal.com/event/4344635", 
                                                                                                                                   "https://duke.libcal.com/event/4337320", "https://duke.libcal.com/event/4396168", 
                                                                                                                                   "https://duke.libcal.com/event/4337307", "https://duke.libcal.com/event/4397616"
                                                                                                          ), location = c("Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Perkins 218", "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Rubenstein Library 349 (Breedlove Conference Room)", 
                                                                                                                          "Bostock 023 Training Room", "Perkins 218", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room")), .Names = c("workshop_id", 
                                                                                                                                                                    "date", "title", "presenter", "workshop_duration_minutes", "workshop_begins", 
                                                                                                                                                                    "workshop_ends", "description", "registration_link", "location"
                                                                                                                          ), row.names = c(NA, -25L), class = c("tbl_df", "tbl", "data.frame"
                                                                                                                          ))


library(googledrive)
library(googlesheets4)
drive_auth()
sheets_auth(token=drive_token())


for(i in 1:nrow(dvs_cal_tbl))
{
    `Attended (x or blank)` <- ""
    `Registration Status (Registered, Waitlist, or Walk-in)` <- ""
    `Workshop Date` <- c(dvs_cal_tbl[[i,2]])
    `Workshop Name` <- c(dvs_cal_tbl[[i,3]])
    WorkshopID <- c(dvs_cal_tbl[[i,1]])
    `First Name` <- ""
    `Last Name` <- ""
    Email <- ""
    `Booking Made` <- ""
    Attendance <- ""
    `Are you affiliated with Duke University, Duke Medical Center, DCRI, or another Duke group?` <- ""
    `Academic Status (or other)` <- ""
    `Discipline or Affiliation` <- ""
    `Institutes, Initiatives, or Program Affiliation` <- ""
    `Where did you hear about this event?` <- ""
    `Have you consulted with Data and Visualization Services before this workshop?` <- ""
    `Would you like to receive more information about DVS events and training?` <- ""
    `I'm interested in registering for this workshop because:` <- ""
    `If other, describe below:` <- ""
    
    ex <- tibble(`Attended (x or blank)`,`Registration Status (Registered, Waitlist, or Walk-in)`,`Workshop Date`,`Workshop Name`, WorkshopID, `First Name`, `Last Name`, Email, `Booking Made`, Attendance, `Are you affiliated with Duke University, Duke Medical Center, DCRI, or another Duke group?`, `Academic Status (or other)`, `Discipline or Affiliation`, `Institutes, Initiatives, or Program Affiliation`, `Where did you hear about this event?`, `Have you consulted with Data and Visualization Services before this workshop?`, `Would you like to receive more information about DVS events and training?`, `I'm interested in registering for this workshop because:`, `If other, describe below:`)
    #ex2 <- tibble(`First Name`, `Last Name`, Email, `Booking cancelled`)
    fn1 <- paste0("attendance_sheets/spring_2020/",dvs_cal_tbl[[i,3]],"_",dvs_cal_tbl[[i,2]],".csv")
    fn2 <- paste0(dvs_cal_tbl[[i,3]],"_",dvs_cal_tbl[[i,2]],".csv")
    test_googlesheets4_upload <- drive_upload(
        media = fn1,
        name = fn2,
        type = "spreadsheet"
    )
   # write_csv(ex, fn1)
    #up_gd <- gs_upload(fn1)
    #up_gd <- up_gd %>% gs_ws_new(ws_title = "Cancellations", input = ex2, trim = TRUE, verbose = FALSE)
}

