---
title: "dvs_cal"
author: "Joel Herndon"
date: "9/11/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
```


First we create a data frame of DVS workshops based on what was libCal at the begining of the fall 2017 semester.



## Fall 2017
```{r Fall 2017 data frame}
dvs_workshops_fall2017_master_20170901 <- structure(list(workshop_id = c("3442483", "3442549", "3442491", 
"3442497", "3442510", "3442538", "3442542", "3433571", "3442555", 
"3442551", "3442573", "3442576", "3442511", "3433537", "3444120", 
"3442601", "3442613", "3442545", "3442643", "3433577", "3442422", 
"3442505", "3443737", "3442642", "3442652", "3433956", "3433957"
), date = structure(c(17420, 17421, 17421, 17422, 17423, 17427, 
17429, 17429, 17434, 17435, 17436, 17438, 17441, 17442, 17452, 
17455, 17456, 17456, 17457, 17458, 17458, 17463, 17463, 17477, 
17479, 17569, 17598), class = "Date"), title = c("Intro to R: Data Transformations, Analysis, and Data Structures", 
"Intro to ArcGIS Desktop", "Introduction to Effective Data Visualization", 
"Data Management Fundamentals", "Easy Interactive Charts and Maps with Tableau", 
"Reproducibility: Data Management, Git, and RStudio", "Data Visualization with Excel", 
"Introduction to Stata", "Visualization in R using ggplot2", 
"Writing a Data Management Plan", "Intro to QGIS", "Adobe Illustrator to Enhance Charts and Graphs", 
"Mapping with R", "Increasing Openness and Reproducibility in Quantitative Research", 
"Visualizing Qualitative Data", "Cloud Mapping Applications", 
"Designing Infographics in PowerPoint", "Intro to R:  Data Transformations, Analysis, and Data Structures", 
"Finding a Home for Your Data: An Introduction to Archives and Repositories", 
"Introduction to Stata", "Developing Interactive Websites with R and Shiny", 
"Consent, Data Sharing and Data Reuse", "Intro to ArcGIS Pro", 
"Research Collaboration Strategies and Tools", "Tidy Data Visualization with Python", 
"Introduction to Stata", "Introduction to Stata"), presenter = c("Joel Herndon & John Little", 
"Mark Thomas", "Angela Zoss", "Jen Darragh, Mara Sedlins & Sophia Lafferty-Hess", 
"Eric Monson", "Jen Darragh, John Little & Sophia Lafferty-Hess", 
"Angela Zoss", "Ryan Denniston", "Angela Zoss", "Jen Darragh & Sophia Lafferty-Hess", 
"Mark Thomas", "Eric Monson", "John Little & Mark Thomas", "Center for Open Science", 
"Angela Zoss", "Mark Thomas", "Eric Monson", "Joel Herndon & John Little", 
"Jen Darragh, Mara Sedlins & Sophia Lafferty-Hess", "Ryan Denniston", 
"Joel Herndon", "Jen Darragh", "Mark Thomas", "Jen Darragh, Mara Sedlins & Sophia Lafferty-Hess", 
"Eric Monson", "Ryan Denniston", "Ryan Denniston"), workshop_duration_minutes = c(120, 
120, 60, 120, 120, 120, 120, 120, 120, 60, 120, 120, 120, 180, 
90, 120, 120, 120, 120, 120, 120, 60, 120, 120, 120, 120, 120
), workshop_begins = structure(c(1505151000, 1505224800, 1505235600, 
1505322000, 1505408400, 1505755800, 1505914200, 1505926800, 1506358800, 
1506452400, 1506531600, 1506690000, 1506965400, 1507035600, 1507901400, 
1508173200, 1508247000, 1508261400, 1508349600, 1508421600, 1508434200, 
1508864400, 1508864400, 1510077600, 1510250400, 1518026400, 1520521200
), tzone = "America/New_York", class = c("POSIXct", "POSIXt")), 
    workshop_ends = structure(c(1505158200, 1505232000, 1505239200, 
    1505329200, 1505415600, 1505763000, 1505921400, 1505934000, 
    1506366000, 1506456000, 1506538800, 1506697200, 1506972600, 
    1507046400, 1507906800, 1508180400, 1508254200, 1508268600, 
    1508356800, 1508428800, 1508441400, 1508868000, 1508871600, 
    1510084800, 1510257600, 1518033600, 1520528400), tzone = "America/New_York", class = c("POSIXct", 
    "POSIXt")), description = c("A gentle introduction to the basics of R using RStudio.  Learn about managing your R projects, data types, variable assignments, data structures, and packages such as tidyverse (dplyR) and ggvis.", 
    "Do you want to find out how geographic information (GIS) software can aid your research? This class will provide an overview of how ArcGIS Desktop software can help you analyze or visualize digital data that has a locational component, as well as discuss starting points for obtaining data. Examples will focus on social science data, but attendees are encouraged to ask questions regarding their own needs and will be welcome to make one-on-one appointments later for more focused instruction.", 
    "Data visualization is an increasingly important skill for researchers in all disciplines, but design skills are seldom taught explicitly.  This talk will focus on a few basic design principles than can help you improve your visualizations, regardless of your discipline or choice of software.  We will cover effective design choices for visualization and how to get started when visualizing your data.", 
    "This workshop introduces data management practices to consider throughout the research lifecycle: planning, organization, documentation, storage and backup, sharing, citation, and preservation. The workshop will offer an overview of general recommendations that are relevant across disciplines and will point attendees to additional resources at Duke and beyond.", 
    "Tableau Public (available for both Windows and Mac) is free software that allows individuals to quickly and easily explore their data with a wide variety of visual representations, as well as create interactive web-based visualization dashboards. This workshop will focus on using Tableau Public to create data visualizations, starting with an overview of how the program thinks about data, common data manipulation and loading, and the terminology used. Activities will include a sample data visualization and mapping project, which will give people hands-on experience using Tableau’s basic chart types and dashboard creation tools. We will also discuss publishing to the Tableau Public web server and related services and tools, like the full Tableau Desktop application (free for full-time students).", 
    "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. This workshop will introduce some general data management strategies that can increase the reproducibility of your work. You will also learn through hands-on exercises how to harness two specific tools, git and RStudio, to support the execution of more reproducible research projects. Git is a powerful version control system and RStudio is an open-source statistical software program. No previous experience with Git or R is required for this workshop.", 
    "For many basic charts and graphs, Excel is one of the easiest ways to create a data visualization.  Figuring out how to get Excel to produce exactly the chart you want, however, can be a bit of a headache.  In this workshop, we will learn how to create and modify many different charts within Excel, in addition to learning how PivotTables can help arrange the data in the best way for the chart we want.", 
    "Stata for Research focuses on the core concepts of using Stata. This workshop provides a hands on overview of how to load, manage, and analyze data using Stata. The workshop will also include a brief introduction to Stata graphics as well. No previous experience with Stata is required.", 
    "Data science skills are increasingly important for research and industry projects.  With complex data science projects, however, come complex needs for understanding and communicating analysis processes and results.  Ultimately, an analyst's data science toolbox is incomplete without visualization skills.  Incorporating effective visualizations directly into the analysis tool you are using can facilitate quick data exploration, streamline your research process, and improve the reproducibility of your research.", 
    "This workshop will be a deep dive into the process of writing a data management plan (DMP) using the DMPTool. To make the most of this workshop, attendees are encouraged to bring a “live” DMP that they are ready to begin or are currently in the process of writing.  Attendees without active DMPs may write a “test” DMP based on who they would typically apply to for research funding.  The “test” DMP can then serve as a useful reference when it is time to write a live plan. The instructors (both Research Data Management Consultants) will be on-hand to provide individual help during the writing portion of the workshop as needed and, following the workshop, are available to review plans through the DMPTool at any point up to final submission. ", 
    "Looking for an open source option for GIS? QGIS is free and it is one alternative to using ArcGIS. In this workshop we will demonstrate how to import and analyze data in QGIS and discuss the benefits of using QGIS over other GIS software. In the process, we'll go over some general GIS concepts such as layers, types of GIS files, and projections.", 
    "In this workshop, you will learn the basics of using Adobe Illustrator, the professional standard in vector graphics software, for fine-tuning charts and graphs created in other programs like Excel, Matlab and R. Many people avoid using Illustrator because of its steep learning curve, but you will see that once you know a few basic tools, it is quite easy to give all your work a consistent look, extra highlights and annotations, and that professional edge. There are no prerequisites – we will start with the basics. (Note that the material presented here is a more complete and expanded treatment of the last section of my previous Illustrator workshops where chart modification always got squeezed into the last half-hour, which was not enough time.)", 
    "R has become a popular mapping option for those who want to easily switch between spatial and statistical analysis and reproduce/share the code easily.  This workshop will demonstrate how to import and view shapefiles, run statistical analysis, and create a leaflet map which can be used online.  Prerequisites: Intro to R: Data Transformations, Analysis, and Data Structures.  Please attend this workshop or watch the video. Knowledge of GIS concepts is recommended.", 
    "There are many actions researchers can take to increase the openness and reproducibility of their work. Please join us for a workshop, hosted by the Center for Open Science, to learn easy, practical steps researchers can take to increase the reproducibility of their work. The workshop will be hands-on. Using example studies, attendees will actively participate in creating a reproducible project from start to finish. Topics covered include project documentation, version control, pre-analysis plans, and open source tools like the Open Science Framework.", 
    "So many of the tools that have been developed for data visualization focus on data that are in spreadsheet format, especially data that are number-heavy.  For qualitative research, numerical data may not be the primary focus, or the numerical data may be difficult to visualize for other reasons.  This workshop will explore some of the complications of trying to visualize qualitative data, walking through examples of different types of qualitative data projects and the visualizations that have been produced from those projects.  Exercises will help attendees work through the process of developing visualizations for sample qualitative projects.  The workshop will include recommendations for tools that may be useful, but we will focus more on the process of identifying possible visual elements within a qualitative data project than on a specific software application.", 
    "Compare and contrast several products intended for geospatial visualization (e.g., a map to embed in a blog or PowerPoint, or for a poster session) and, in some cases, for GIS data analysis.  We'll focus on ArcGIS Online, which is a companion to the ArcGIS client that allows members of a group to store and share spatial data online, and that can be used independently or in conjunction with the ArcGIS client.  Also, we'll touch on several other cloud-based options for creating simple maps for sharing.", 
    "The “infographics” style of presenting information and telling visual stories is popular both for internal reporting and for trying to reach and teach the general public. There are many desktop and online tools that can be used to compose static infographics, but we will focus on Microsoft PowerPoint because so many people have free access to it on campus and already have some comfort with it as a visual communications tool. This workshop will give a brief introduction to graphic design and storytelling principles, as well as hands-on practice with using PowerPoint to create icons and other vector shapes to combine with text and visualizations to tell compelling and eye-catching data stories. There are no prerequisites, but some experience using PowerPoint will be helpful.", 
    "A gentle introduction to the basics of R using RStudio.  Learn about managing your R projects, data types, variable assignments, data structures, and packages such as tidyverse (dplyR) and ggvis.", 
    "Publishing and preserving research data within a trusted repository helps researchers comply with funder and journal data sharing policies, supports the discovery of and access to data, and can result in more visibility and higher impact for research projects. This workshop will provide an overview of the different types of repositories and the overall role of repositories within the data sharing landscape. Key repositories in various disciplines will be explored, and attendees will learn about resources for locating and assessing repositories. Attendees will also have an opportunity to locate appropriate repositories for their own research. ", 
    "Stata for Research focuses on the core concepts of using Stata. This workshop provides a hands on overview of how to load, manage, and analyze data using Stata. The workshop will also include a brief introduction to Stata graphics as well. No previous experience with Stata is required.", 
    "Learn how to leverage your knowledge of R and RMarkdown to create compelling, interactive website and interactive documents using the Shiny web application framework.  Shiny makes it easy to transition from desktop based analysis and visualizations to interactive websites without having to learn HTML, CSS, and javascript.  This workshop provides an overview of the shiny framework along with examples and exercises designed to build confidence in developing shiny based documents and websites.  ", 
    "Research involving humans requires multiple approaches to protect participants’ anonymity. If you are planning to (or are required to) share your human subjects’ data outside of your original project team, or plan to re-use data you collected previously for a new research project, you will need to design a consent form/consent protocol that properly addresses these situations.  This workshop will present various research scenarios with examples of how consent protocols should be developed.", 
    "ArcGIS Pro is a newly designed interface to the tried-and-true ArcGIS desktop software. It has essentially the same functions, but with more of a MS-Office interface. As a native 64-bit program, it also has superior performance. There are a few nice feature enhancements such as multiple layouts in a single project.  It's more fully integrated with ArcGIS Online, and users will need to have created an Duke ArcGIS Online account. An administrator will activate your ArcGIS Pro license after you've created an ArcGIS Online account.", 
    "Scholars increasingly work on collaborative research projects. Collaborative projects often bring together partners across disciplines, institutions, and sectors. These projects present opportunities for innovation but also raise challenges for the development of efficient and effective workflows and the management of data. This workshop will examine considerations for collaborative research and present some strategies for developing and documenting workflows as well as methods for storing and sharing data. We will also look at some tools (i.e., Box, OSF, PRDN, etc.) available at Duke that can be used to support these types of projects. ", 
    "Python can be a great option for exploration, analysis and visualization of tabular data, like spreadsheets and CSV files, if you know which tools to use and how to get started. This workshop will take you through some practical examples of using Python and the Pandas module inside a Jupyter notebook, to load data, transform it into a standard “tidy” format, and visualize it with Seaborn (or another similar module). There are no prerequisites for this workshop – familiarity with the Python programming language is not required, but you will probably find it easier to follow if you have a little coding experience since we will not be giving an overview of the language itself. Instead, the focus will be on learning how to use the language through conceptual understanding and recipes for specific, commonly-useful tasks.", 
    "Stata for Research focuses on the core concepts of using Stata. This workshop provides a hands on overview of how to load, manage, and analyze data using Stata. The workshop will also include a brief introduction to Stata graphics as well. No previous experience with Stata is required.", 
    "Stata for Research focuses on the core concepts of using Stata. This workshop provides a hands on overview of how to load, manage, and analyze data using Stata. The workshop will also include a brief introduction to Stata graphics as well. No previous experience with Stata is required."
    ), registration_link = c("http://duke.libcal.com/event/3442483", 
    "http://duke.libcal.com/event/3442549", "http://duke.libcal.com/event/3442491", 
    "http://duke.libcal.com/event/3442497", "http://duke.libcal.com/event/3442510", 
    "http://duke.libcal.com/event/3442538", "http://duke.libcal.com/event/3442542", 
    "http://duke.libcal.com/event/3433571", "http://duke.libcal.com/event/3442555", 
    "http://duke.libcal.com/event/3442551", "http://duke.libcal.com/event/3442573", 
    "http://duke.libcal.com/event/3442576", "http://duke.libcal.com/event/3442511", 
    "http://duke.libcal.com/event/3433537", "http://duke.libcal.com/event/3444120", 
    "http://duke.libcal.com/event/3442601", "http://duke.libcal.com/event/3442613", 
    "http://duke.libcal.com/event/3442545", "http://duke.libcal.com/event/3442643", 
    "http://duke.libcal.com/event/3433577", "http://duke.libcal.com/event/3442422", 
    "http://duke.libcal.com/event/3442505", "http://duke.libcal.com/event/3443737", 
    "http://duke.libcal.com/event/3442642", "http://duke.libcal.com/event/3442652", 
    "http://duke.libcal.com/event/3433956", "http://duke.libcal.com/event/3433957"
    )), .Names = c("workshop_id", "date", "title", "presenter", 
"workshop_duration_minutes", "workshop_begins", "workshop_ends", 
"description", "registration_link"), class = c("tbl_df", "tbl", 
"data.frame"), row.names = c(NA, -27L))

#write_delim(dvs_workshops_fall2017_master_20170901, path = ".", delim = "\t")
```


#Spring 2018

```{r Spring 2018 data frame}
dvs_workshops_spring_2018_master_20180105 <- structure(list(workshop_id = c("3735183", "3735186", "3734408", 
"3742605", "3820621", "3731617", "3820640", "3734428", "3735226", 
"3734431", "3735232", "3735207", "3742735", "3433956", "3735229", 
"3731660", "3905863", "3770373", "3869275", "3731669", "3997795", "3735220", 
"3735957", "3433957", "3776408", "3735965"), date = structure(c(17543, 
17547, 17550, 17553, 17554, 17555, 17556, 17556, 17557, 17560, 
17561, 17563, 17567, 17569, 17571, 17576, 17576, 17581, 17583, 
17588, 17590, 17596, 17597, 17598, 17618, 17625), class = "Date"), title = c("Easy Charts and Maps with Tableau", 
"Introduction to Effective Data Visualization", "Intro to R: Data Transformations, Analysis, and Data Structures", 
"Intro to QGIS", "R Markdown", "Data Management Fundamentals", 
"Shiny", "Mapping with R", "Infographics in PowerPoint", "Reproducibility: Data Management, Git, and RStudio", 
"Adobe Illustrator for Diagrams", "Visualization in R using ggplot2", 
"Intro to ArcGIS Pro", "Introduction to Stata", "Custom Interactive Diagrams in LucidChart", 
"Introduction to the Open Science Framework", "Story Maps with ArcGIS Online", 
"Map Design", "Getting Started with NVivo 11 for Windows", "OSF + TIER Protocol: Designing a reproducible workflow", "Intro to R: Data Transformations, Analysis, and Data Structures", 
"Designing Effective Academic Posters", "Developing a Good Informed Consent Process", 
"Introduction to Stata", "Publishing Data with Research and Other Strategies for Increasing Your Impact", 
"Managing Sensitive Data"), presenter = c("Eric Monson", "Angela Zoss", 
"Joel Herndon & John Little", "Mark Thomas", "Dr. Mine Çetinkaya-Rundel", 
"Jen Darragh, Mara Sedlins & Sophia Lafferty-Hess", "Dr. Mine Çetinkaya-Rundel", 
"John Little", "Eric Monson", "John Little & Sophia Lafferty-Hess", 
"Eric Monson", "Angela Zoss", "Mark Thomas", "Ryan Denniston", 
"Angela Zoss", "Mara Sedlins & Sophia Lafferty-Hess", "Drew Keener", 
"Drew Keener", "Brittany Wofford & Mara Sedlins", "Mara Sedlins & Sophia Lafferty-Hess", "John Little & Joel Herndon",
"Angela Zoss & Eric Monson", "Jen Darragh, Holly Williams-Stafford", 
"Ryan Denniston", "Haley Walton, Mara Sedlins & Sophia Lafferty-Hess", 
"Jen Darragh & Mara Sedlins & Andy Ingham, & Holly Williams-Stafford"
), workshop_duration_minutes = c(120, 60, 120, 120, 120, 120, 
120, 120, 120, 120, 120, 120, 120, 120, 120, 60, 120, 90, 90, 
120, 120, 120, 120, 120, 120, 90), workshop_begins = structure(c(1515765600, 
1516122000, 1516384800, 1516633200, 1516716000, 1516816800, 1516888800, 
1516903200, 1516975200, 1517248800, 1517320800, 1517495400, 1517853600, 
1518026400, 1518184800, 1518620400, 1518631200, 1519065000, 1519243200, 
1519668000, 1519830000, 1520344800, 1520449200, 1520521200, 1522260000, 1522861200
), tzone = "America/New_York", class = c("POSIXct", "POSIXt")), 
    workshop_ends = structure(c(1515772800, 1516125600, 1516392000, 
    1516640400, 1516723200, 1516824000, 1516896000, 1516910400, 
    1516982400, 1517256000, 1517328000, 1517502600, 1517860800, 
    1518033600, 1518192000, 1518624000, 1518638400, 1519070400, 
    1519248600, 1519675200, 1519837200, 1520352000, 1520456400, 1520528400, 
    1522267200, 1522866600), tzone = "America/New_York", class = c("POSIXct", 
    "POSIXt")), description = c("Tableau Public (available for both Windows and Mac) is free software that allows individuals to quickly and easily explore their data with a wide variety of visual representations, as well as create interactive web-based visualization dashboards. This workshop will focus on using Tableau Public to create data visualizations, starting with an overview of how the program thinks about data, common data manipulation and loading, and the terminology used. Activities will include a sample data visualization and mapping project, which will give people hands-on experience using Tableau’s basic chart types and dashboard creation tools. We will also discuss publishing to the Tableau Public web server and related services and tools, like the full Tableau Desktop application (free for full-time students).", 
    "Data visualization is an increasingly important skill for researchers in all disciplines, but design skills are seldom taught explicitly.  This talk will focus on a few basic design principles than can help you improve your visualizations, regardless of your discipline or choice of software.  We will cover effective design choices for visualization and how to get started when visualizing your data.", 
    "A gentle introduction to the basics of R using RStudio.  Learn about managing your R projects, data types, variable assignments, data structures, and packages such as tidyverse (dplyR) and ggvis.", 
    "Looking for an open source option for GIS? QGIS is free and it is one alternative to using ArcGIS. In this workshop we will demonstrate how to import and analyze data in QGIS and discuss the benefits of using QGIS over other GIS software. In the process, we'll go over some general GIS concepts such as layers, types of GIS files, and projections.", 
    "R Markdown provides an authoring framework for data science. You can use a single R Markdown file to both save and execute code or generate high quality reports that can be shared with an audience. This hands-on workshop will demonstrate the how to create fully reproducible static and dynamic R Markdown reports in a variety of output formats and will provide tips and tricks for customization.", 
    "This workshop introduces data management practices to consider throughout the research lifecycle: planning, organization, documentation, storage and backup, sharing, citation, and preservation. The workshop will offer an overview of general recommendations that are relevant across disciplines and will point attendees to additional resources at Duke and beyond.", 
    "Shiny is an R package that makes it easy to build interactive web apps straight from R. You can host standalone apps on a webpage or embed them in R Markdown documents or build dashboards. This workshop will introduce you to the basics of building web applications with Shiny, essentials of reactive programming, and how to customize and deploy your apps for others to use.", 
    "R has become a popular and reproducible option for supporting spatial and statistical analysis. This hands-on workshop will demonstrate how to plot x/y coordinates; how to generate thematic chloropleths with US Census and other federal data; import, view and produce shapefiles; and create leaflet maps for viewing on the web.", 
    "The “infographics” style of presenting information and telling visual stories is popular both for internal reporting and for trying to reach and teach the general public. There are many desktop and online tools that can be used to compose static infographics, but we will focus on Microsoft PowerPoint because so many people have free access to it on campus and already have some comfort with it as a visual communications tool. This workshop will give a brief introduction to graphic design and storytelling principles, as well as hands-on practice with using PowerPoint to create icons and other vector shapes to combine with text and visualizations to tell compelling and eye-catching data stories. There are no prerequisites, but some experience using PowerPoint will be helpful.", 
    "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. This workshop will introduce some general data management strategies that can increase the reproducibility of your work. You will also learn through hands-on exercises how to harness two specific tools, git and RStudio, to support the execution of more reproducible research projects. Git is a powerful version control system and RStudio is an open-source statistical software program. ", 
    "In this workshop, you will learn the basics of using Adobe Illustrator, the professional standard in vector graphics software for creating diagrams and infographics. Many people avoid using it because of its steep learning curve, but you will see that it is quite easy to combine simple shapes to create interesting and clear diagrams, and to give all your work that professional edge. There are no prerequisites.", 
    "Data science skills are increasingly important for research and industry projects.  With complex data science projects, however, come complex needs for understanding and communicating analysis processes and results.  Ultimately, an analyst's data science toolbox is incomplete without visualization skills.  Incorporating effective visualizations directly into the analysis tool you are using can facilitate quick data exploration, streamline your research process, and improve the reproducibility of your research.", 
    "ArcGIS Pro is a newly designed interface to the tried-and-true ArcGIS desktop software. It has essentially the same functions, but with more of a MS-Office interface. As a native 64-bit program, it also has superior performance. There are a few nice feature enhancements such as multiple layouts in a single project.  It's more fully integrated with ArcGIS Online, and users will need to have created an Duke ArcGIS Online account. An administrator will activate your ArcGIS Pro license after you've created an ArcGIS Online account.", 
    "Stata for Research focuses on the core concepts of using Stata. This workshop provides a hands on overview of how to load, manage, and analyze data using Stata. The workshop will also include a brief introduction to Stata graphics as well. No previous experience with Stata is required.", 
    "Diagrams, a type of visualization that focuses on shapes and connectors, can be used to visualize a structure, process, or concept.  Diagrams can be created in any standard graphic design or drawing programs, but there are only a few general diagramming tools that are specially designed to assist with spacial arrangement and shape choice, and many of those tools focus on creating static, print-based diagrams. LucidChart, available to members of the Duke community, can create engaging diagrams with interactive components that can be shared and embedded online. ", 
    "The Open Science Framework (OSF) is a free, open source project management tool developed and maintained by the Center for Open Science. The OSF can help scholars manage their workflow, organize their materials, and share all or part of a project with the broader research community. This workshop will demonstrate some of the key functionalities of the tool including how to structure your materials, manage permissions, version content, integrate with third-party tools (such as Box, GitHub, or Mendeley), share materials, register projects, and track usage. ", 
    "ArcGIS Online is a companion to the ArcGIS client that allows members of a group to store and share spatial data online and to perform GIS analysis in a browser environment. It can be used independently or in conjunction with an ArcGIS client. We'll focus on its Story Maps, which provide a way to disseminate a finished product in an interactive web interface. The audience doesn't need to know or have access to any ArcGIS products. Story Maps allow the integration of other media (photos, text, videos) and allow following changes over space and time.", 
    "Making maps is a creative rather than a purely technical process. Even if you can expertly use the latest and most advanced tools, you still have to make design decisions based on your specific audience, data, and goals. This workshop will present an overview of concepts in cartography and provide practical techniques for creating effective, visually appealing maps. We will explore design principles by analyzing plenty of examples. No specific software experience or GIS knowledge is required.", 
    "This workshop will introduce researchers to the basics of NVivo 11 Pro for Windows, a qualitative data analysis software. Participants will learn the foundations needed to begin analyzing data in NVivo. Topics will include how to import data, create nodes and code, and  run basic queries. Although Mac users are welcome to attend, this workshop will primarily focus on using NVivo in the Windows environment, though we will discuss some of the differences between the two versions of the software.", 
    "The Open Science Framework is a free online system for managing and sharing research materials throughout the research cycle, and the TIER Protocol is a workflow for maintaining well-organized documentation of your data and analyses. This workshop will introduce you to key features of the OSF and demonstrate how it can be used in conjunction with TIER to facilitate reproducible research practices, collaboration, and best practices in data management.", 
    "A gentle introduction to the basics of R using RStudio. Learn about managing your R projects, data types, variable assignments, data structures, and packages such as: tidyverse (including dplyR).  Students will also gain brief introductions to visualizaton with ggvis and mapping with leaflet. Attendees will have the opportunity of supplementing the materials covered in this workshop with free academic access to the interactive training at DataCamp.com.",
    "Presenting research in an accurate and visually appealing way can have a huge impact on the communication of research to a broader audience. Academic posters are some of the most visual outputs of a research project, and becoming familiar with good strategies for poster design allows researchers to take full advantage of the opportunity to network with colleagues and promote their own research. This workshop will cover basic considerations for designing effective academic posters, including use of color, layout, fonts/typography, and software choices. Hands-on activities throughout the workshop will also help participants gain comfort with how to apply general principles to the design of a real poster.  This workshop will focus on PowerPoint for poster creation, but many of the techniques will apply to more powerful programs like Adobe Illustrator.", 
    "In this forum you will learn how to develop fully comprehensible, participant-friendly consent protocols. With numerous research funders and journal publishers requiring data management and sharing plans, consent forms and protocols need to address how participant privacy will be protected throughout a project’s lifecycle and how and what data will be shared. The workshop includes interactive exercises where you will assess consent form language to ensure that it is appropriate for the target study population and addresses data sharing in a responsible way. ", 
    "Stata for Research focuses on the core concepts of using Stata. This workshop provides a hands on overview of how to load, manage, and analyze data using Stata. The workshop will also include a brief introduction to Stata graphics as well. No previous experience with Stata is required.", 
    "Scholars can and do communicate their research in various ways. While peer-reviewed journal publications remain the primary outlet for sharing the key results of research projects, there are growing norms (and expectations) that the underlying data from projects should also be published. In this workshop, we will look at 1) strategies to effectively publish data; 2) journal policies related to data sharing; 3) new types of publications such as data articles and registered reports; and 4) strategies for increasing and measuring the impact of your research. There will also be a hands-on portion of the workshop where participants will create their own ORCID identifier. ", 
    "In the course of your research you may collect, interact with or analyze data that are classified as “Sensitive” or \"Restricted\" according to Duke's data classification standard. In this workshop we will examine common sensitive data types, how Duke’s IRB and Information Technology Security Office (ITSO) expects you to protect that data throughout your project’s lifecycle and the resources available to you for sensitive data storage and analysis, data de-identification, and data archiving and sharing."
    ), registration_link = c("https://duke.libcal.com/event/3735183", 
    "https://duke.libcal.com/event/3735186", "https://duke.libcal.com/event/3734408", 
    "https://duke.libcal.com/event/3742605", "https://duke.libcal.com/event/3820621", 
    "https://duke.libcal.com/event/3731617", "https://duke.libcal.com/event/3820640", 
    "https://duke.libcal.com/event/3734428", "https://duke.libcal.com/event/3735226", 
    "https://duke.libcal.com/event/3734431", "https://duke.libcal.com/event/3735232", 
    "https://duke.libcal.com/event/3735207", "https://duke.libcal.com/event/3742735", 
    "https://duke.libcal.com/event/3433956", "https://duke.libcal.com/event/3735229", 
    "https://duke.libcal.com/event/3731660", "https://duke.libcal.com/event/3905863", 
    "https://duke.libcal.com/event/3770373",
    "https://duke.libcal.com/event/3869275", 
    "https://duke.libcal.com/event/3731669",
    "https://duke.libcal.com/event/3997795",
    "https://duke.libcal.com/event/3735220", 
    "https://duke.libcal.com/event/3735957",
    "https://duke.libcal.com/event/3433957", 
    "https://duke.libcal.com/event/3776408",
    "https://duke.libcal.com/event/3735965"
    ), location = c("Bostock 023 Training Room", "Perkins 217", 
    "Bostock 023 Training Room", "Bostock 023 Training Room", 
    "Bostock 023 Training Room", "Perkins 217", "Bostock 023 Training Room", 
    "Bostock 023 Training Room", "Bostock 023 Training Room", 
    "Bostock 023 Training Room", "Bostock 023 Training Room", 
    "Bostock 023 Training Room", "Bostock 023 Training Room", 
    "Bostock 023 Training Room", "Bostock 023 Training Room", 
    "Bostock 023 Training Room", "Perkins 218", "Perkins 218", 
    "Bostock 023 Training Room", "Bostock 023 Training Room", "Bostock 023 Training Room",
    "Bostock 023 Training Room", "Rubenstein Library 153 (Holsti-Anderson Family Assembly Room)", "Bostock 023 Training Room", 
    "Perkins 217", "Rubenstein Library 153 (Holsti-Anderson Family Assembly Room)")), .Names = c("workshop_id", 
"date", "title", "presenter", "workshop_duration_minutes", "workshop_begins", 
"workshop_ends", "description", "registration_link", "location"
), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, 
-26L))

#write_delim(dvs_workshops_spring_2018_master_20180105, path = ".", delim = "\t")


#Fall 2018 
dvs_workshops_fall_2018_master_20180903 <- structure(list(workshop_id = c("4337268", "4349368", "4335566", 
                               "4341120", "4350030", "4337253", "4335574", "4341127", "4335577", 
                               "4350034", "4350882", "4337315", "4428595", "4335582", "4475727", 
                               "4350042", "4350915", "4335586", "4337318", "4335665", "4344635", 
                               "4337320", "4396168", "4337307", "4397616"), date = structure(c(17778, 
                                                                                               17779, 17785, 17786, 17787, 17792, 17793, 17794, 17799, 17799, 
                                                                                               17800, 17806, 17806, 17807, 17812, 17815, 17815, 17820, 17827, 
                                                                                               17834, 17835, 17842, 17843, 17848, 17849), class = "Date"), title = c("Intro to R: Data Transformations, Data Structures, and the Tidyverse", 
                                                                                                                                                                     "Web Mapping", "Building Blocks for Reproducibility: Concepts and Practices", 
                                                                                                                                                                     "Intro to ArcGIS Pro", "Creating Infographics in PowerPoint", 
                                                                                                                                                                     "Visualization in R using ggplot2", "Data Management 101 for Social Scientists", 
                                                                                                                                                                     "Intro to QGIS", "Building Blocks for Reproducibility: RStudio and Git", 
                                                                                                                                                                     "Adobe Illustrator for Diagrams", "Story Maps", "R Markdown: tips for authoring reproducible documents, slide presentations, web dashboards and more", 
                                                                                                                                                                     "Introduction to Stata", "Data Management 101 for Humanists", 
                                                                                                                                                                     "Ethics and Visualization", "Tidy Data in Python with JupyterLab", 
                                                                                                                                                                     "Map Design", "Building Blocks for Reproducibility: GitHub and GitLab", 
                                                                                                                                                                     "Mapping with R", "Building Blocks for Reproducibility: Open Science Framework (OSF)", 
                                                                                                                                                                     "Data Management 101 for Scientists", "Shiny App Development with Dr. Mine Çetinkaya-Rundel", 
                                                                                                                                                                     "Finding a Home for Your Data: An Introduction to Archives & Repositories", 
                                                                                                                                                                     "Tidying hierarchical data from the web with Professor Colin Rundel", 
                                                                                                                                                                     "Building Blocks for Reproducibility: The TIER Protocol"), presenter = c("John Little", 
                                                                                                                                                                                                                                              "Drew Keener", "April Clyburne-Sherin", "Mark Thomas", "Eric Monson", 
                                                                                                                                                                                                                                              "Angela Zoss", "Jen Darragh & Sophia Lafferty-Hess & Lorrie Schmid", 
                                                                                                                                                                                                                                              "Mark Thomas", "John Little", "Eric Monson", "Drew Keener", "John Little", 
                                                                                                                                                                                                                                              "Ryan Denniston", "Jen Darragh, Sophia Lafferty-Hess & Liz Milewicz", 
                                                                                                                                                                                                                                              "Eric Monson & Angela Zoss", "Eric Monson", "Drew Keener", "John Little", 
                                                                                                                                                                                                                                              "John Little", "Jen Darragh & Sophia Lafferty-Hess", "Jen Darragh, Elena Feinstein & Sophia Lafferty-Hess", 
                                                                                                                                                                                                                                              "Mine Çetinkaya-Rundel", "Jen Darragh & Sophia Lafferty-Hess", 
                                                                                                                                                                                                                                              "Professor Colin Rundel", "Jen Darragh & Sophia Lafferty-Hess"
                                                                                                                                                                     ), workshop_duration_minutes = c(120, 120, 120, 120, 120, 120, 
                                                                                                                                                                                                      120, 120, 60, 120, 120, 120, 120, 120, 120, 120, 90, 60, 120, 
                                                                                                                                                                                                      60, 120, 120, 120, 120, 60), workshop_begins = structure(c(1536082200, 
                                                                                                                                                                                                                                                                 1536166800, 1536674400, 1536771600, 1536843600, 1537291800, 1537376400, 
                                                                                                                                                                                                                                                                 1537462800, 1537884000, 1537894800, 1537981200, 1538488800, 1538499600, 
                                                                                                                                                                                                                                                                 1538586000, 1539007200, 1539262800, 1539279000, 1539698400, 1540314000, 
                                                                                                                                                                                                                                                                 1540908000, 1541005200, 1541602800, 1541700000, 1542121200, 1542207600
                                                                                                                                                                                                      ), tzone = "America/New_York", class = c("POSIXct", "POSIXt")), 
               workshop_ends = structure(c(1536089400, 1536174000, 1536681600, 
                                           1536778800, 1536850800, 1537299000, 1537383600, 1537470000, 
                                           1537887600, 1537902000, 1537988400, 1538496000, 1538506800, 
                                           1538593200, 1539014400, 1539270000, 1539284400, 1539702000, 
                                           1540321200, 1540911600, 1541012400, 1541610000, 1541707200, 
                                           1542128400, 1542211200), tzone = "America/New_York", class = c("POSIXct", 
                                                                                                          "POSIXt")), description = c("A gentle introduction to R and the Tidyverse using RStudio. Learn about managing your R projects, data types, variable assignments, data structures, and packages such as: tidyverse (dplyR) and ggvis. Attendees will have the opportunity of supplementing the materials covered in this workshop with free academic access to the interactive training workshops at DataCamp.com.", 
                                                                                                                                      "This introductory workshop will teach you how to easily build interactive, online maps. After discussing general mapping concepts and technologies, we will present step-by-step tutorials for ArcGIS Online, a cloud-based mapping platform. Topics will include aspects of adding data, creating and styling maps, publishing web applications, and using spatial analysis tools.", 
                                                                                                                                      "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. DVS is offering a workshop series that will introduce the concepts, practices and tools that will help increase the reproducibility of your work.", 
                                                                                                                                      "ArcGIS Pro is a newly designed interface as an alternative to the tried-and-true ArcGIS desktop software. It has essentially the same functions, but with more of a MS-Office feel. As a native 64-bit program, it also has superior performance. There are a few nice feature enhancements such as multiple layouts in a single project.  It's more fully integrated with ArcGIS Online, and users will need to have created an Duke ArcGIS Online account. An administrator will activate your ArcGIS Pro license after you've created an ArcGIS Online account.", 
                                                                                                                                      "The “infographics” style of presenting information and telling visual stories is popular both for internal reporting and for trying to reach and teach the general public. There are many desktop and online tools that can be used to compose static infographics, but we will focus on Microsoft PowerPoint because so many people have free access to it on campus and already have some comfort with it as a visual communications tool. This workshop will give a brief introduction to graphic design and storytelling principles, as well as hands-on practice with using PowerPoint to create charts, icons and other vector shapes to combine with text and visualizations to tell compelling and eye-catching data stories. There are no prerequisites, but some experience using PowerPoint will be helpful.", 
                                                                                                                                      "Data science skills are increasingly important for research and industry projects.  With complex data science projects, however, come complex needs for understanding and communicating analysis processes and results.  Ultimately, an analyst's data science toolbox is incomplete without visualization skills.  Incorporating effective visualizations directly into the analysis tool you are using can facilitate quick data exploration, streamline your research process, and improve the reproducibility of your research.", 
                                                                                                                                      "Social scientists work with lots of data in their research, be it qualitative or quantitative, primary or secondary. This workshop will introduce data management practices for social scientists to consider and apply throughout the research lifecycle. Good data management practices pertaining to planning, organization, documentation, storage and backup, sharing, citation, and preservation will be presented through a social sciences lens using discipline-based, concrete examples. While good general data management practices are relevant across disciplines, participants working specifically within the social sciences are the intended audience for this workshop. ", 
                                                                                                                                      "Looking for an open source option for GIS? In this workshop we will demonstrate how to import and analyze data in QGIS and discuss the benefits of using QGIS over other GIS software. In the process, we'll go over some general GIS concepts such as layers, types of GIS files, and projections.", 
                                                                                                                                      "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. DVS is offering a workshop series that will introduce the concepts, practices and tools that will help increase the reproducibility of your work.", 
                                                                                                                                      "In this workshop, you will learn the basics of using Adobe Illustrator, the professional standard in vector graphics software for creating diagrams and infographics. Many people avoid using it because of its steep learning curve, but you will see that it is quite easy to combine simple shapes to create interesting and clear diagrams, and to give all your work that professional edge. There are no prerequisites.", 
                                                                                                                                      "This workshop will help you get started telling stories with maps using the Esri Story Map platform. This easy-to-use application integrates maps with narrative text, images, and videos to provide a powerful communication tool for any project with a geographic component. We will explore the capabilities of Story Maps, share best practices for designing effective stories, and guide participants through the process of creating their own Story Map.", 
                                                                                                                                      "Learn how to use this lightweight markup language to compose reproducible reports in many formats: MS Word, PDF, R Notebooks, Web Pages, Slide Presentations, and more. ", 
                                                                                                                                      "Introduction to Stata focuses on the core concepts of using Stata. This workshop provides a hands on overview of how to load, manage, and analyze data using Stata. The workshop will also include a brief introduction to Stata graphics as well. No previous experience with Stata is required.", 
                                                                                                                                      "Humanists work with various media, content and materials (sources) as part of their research. These sources can be considered data. This workshop will introduce data management practices for humanities researchers to consider and apply throughout the research lifecycle.  Good data management practices pertaining to planning, organization, documentation, storage and backup, sharing, citation, and preservation will be presented through a humanities lens with discipline-based, concrete examples. While general good data management practices are relevant across disciplines, participants working specifically within the humanities are the intended audience for this workshop.", 
                                                                                                                                      "Data visualization is an increasingly important skill for researchers in all disciplines, but it is easy to focus more on the mechanics of creating visualizations than on how visualizations relate to ethics. This session introduces participants to core ideas in the ethics of visualization - designing to avoid distortion, designing ethically for broad user communities, developing empathy for people represented within the data, and using reproducibility to increase the transparency of design. This workshop does not require a laptop. (This workshop offers RCR credit.)", 
                                                                                                                                      "Python can be a great option for exploration, analysis and visualization of tabular data, like spreadsheets and CSV files, if you know which tools to use and how to get started. This workshop will take you through some practical examples of using Python and the Pandas module to load data, transform it into a standard “tidy” format, and visualize it with Seaborn (or another similar module). We will also introduce you to working in JupyterLab, the exiting new flexible programming environment which will eventually replace Jupyter Notebooks.", 
                                                                                                                                      "Making maps is a creative rather than a purely technical process. Even if you can expertly use the latest and most advanced tools, you still have to make design decisions based on your specific audience, data, and goals. This workshop will present an overview of concepts in cartography and provide practical techniques for creating effective, visually appealing maps. We will explore design principles by analyzing plenty of examples. No specific software experience or GIS knowledge is required.", 
                                                                                                                                      "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. DVS is offering a workshop series that will introduce the concepts, practices and tools that will help increase the reproducibility of your work.", 
                                                                                                                                      "R has become a popular and reproducible option for supporting spatial and statistical analysis. This hands-on workshop will demonstrate how to plot x/y coordinates; how to generate thematic chloropleths with US Census and other federal data; import shapefiles; and create interactive maps on the web.", 
                                                                                                                                      "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. DVS is offering a workshop series that will introduce the concepts, practices and tools that will help increase the reproducibility of your work.", 
                                                                                                                                      "Scientists work with lots of data both big and small, and in many formats and systems. This workshop will introduce data management practices for scientists to consider and apply throughout the research lifecycle. Good data management practices pertaining to planning, organization, documentation, storage and backup, sharing, citation, and preservation will be presented through a sciences lens using discipline-based, concrete examples. While good general data management practices are relevant across disciplines, participants working specifically within the sciences are the intended audience for this workshop.", 
                                                                                                                                      "Shiny is an R package that makes it easy to build interactive web apps straight from R. You can host stand-alone apps on a webpage or embed them in R Markdown documents or build dashboards. This short course will introduce you to building web applications with Shiny, reactive programming, and customizing and deploying your apps for others to use.", 
                                                                                                                                      "Publishing and preserving research data within a trusted repository helps researchers comply with funder and journal data sharing policies, supports the discovery of and access to data, and can result in more visibility and higher impact for research projects. This workshop will provide an overview of the different types of repositories and the overall role of repositories within the data sharing landscape. Key repositories in various disciplines will be explored and attendees will learn about resources for locating and assessing repositories. Attendees will also have an opportunity to locate appropriate repositories for their own research.", 
                                                                                                                                      "Gathering data from the web presents unique challenges to the researcher. Only rarely is the data we need available as a tidy rectangle that can be easily imported and directly analyzed. During this workshop we will discuss some of the common data formats (e.g. json, xml) and data sources (e.g. APIs, web scraping) as well as the tools / packages / best practices for ingesting these data using the R programming language.", 
                                                                                                                                      "In response to a growing focus on the importance of reproducibility, replication, and transparency in the research endeavor, scholars are adapting their practices and learning new skills and tools. DVS is offering a workshop series that will introduce the concepts, practices and tools that will help increase the reproducibility of your work."
                                                                                                          ), registration_link = c("https://duke.libcal.com/event/4337268", 
                                                                                                                                   "https://duke.libcal.com/event/4349368", "https://duke.libcal.com/event/4335566", 
                                                                                                                                   "https://duke.libcal.com/event/4341120", "https://duke.libcal.com/event/4350030", 
                                                                                                                                   "https://duke.libcal.com/event/4337253", "https://duke.libcal.com/event/4335574", 
                                                                                                                                   "https://duke.libcal.com/event/4341127", "https://duke.libcal.com/event/4335577", 
                                                                                                                                   "https://duke.libcal.com/event/4350034", "https://duke.libcal.com/event/4350882", 
                                                                                                                                   "https://duke.libcal.com/event/4337315", "https://duke.libcal.com/event/4428595", 
                                                                                                                                   "https://duke.libcal.com/event/4335582", "https://duke.libcal.com/event/4475727", 
                                                                                                                                   "https://duke.libcal.com/event/4350042", "https://duke.libcal.com/event/4350915", 
                                                                                                                                   "https://duke.libcal.com/event/4335586", "https://duke.libcal.com/event/4337318", 
                                                                                                                                   "https://duke.libcal.com/event/4335665", "https://duke.libcal.com/event/4344635", 
                                                                                                                                   "https://duke.libcal.com/event/4337320", "https://duke.libcal.com/event/4396168", 
                                                                                                                                   "https://duke.libcal.com/event/4337307", "https://duke.libcal.com/event/4397616"
                                                                                                          ), location = c("Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Perkins 218", "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Rubenstein Library 349 (Breedlove Conference Room)", 
                                                                                                                          "Bostock 023 Training Room", "Perkins 218", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room", "Bostock 023 Training Room", 
                                                                                                                          "Bostock 023 Training Room")), .Names = c("workshop_id", 
                                                                                                                                                                    "date", "title", "presenter", "workshop_duration_minutes", "workshop_begins", 
                                                                                                                                                                    "workshop_ends", "description", "registration_link", "location"
                                                                                                                          ), row.names = c(NA, -25L), class = c("tbl_df", "tbl", "data.frame"
                                                                                                                          ))
```


